In [1]:
                                          #Load the Bookings dataframe
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
import warnings
warnings.filterwarnings("ignore")
import mysql.connector
import sqlalchemy

In [2]:
bookings_df=pd.read_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\bookings.csv")
bookings_df.head()

,booking_id,booking_date,booking_time,day_of_week,is_weekend,hour_of_day,city,pickup_location,drop_location,vehicle_type,...,actual_ride_time_min,traffic_level,weather_condition,base_fare,surge_multiplier,booking_value,booking_status,incomplete_ride_reason,customer_id,driver_id
0,B_000001,2025-12-11,00:07:00,Thursday,0,0,Mumbai,Loc_19,Loc_16,Bike,...,NaN,High,Heavy Rain,76.12,2.0,148.22,Cancelled,NaN,C_005097,D_004592
1,B_000002,2025-07-07,06:13:00,Monday,0,6,Mumbai,Loc_32,Loc_38,Cab,...,42.28,Medium,Heavy Rain,254.15,1.8,465.85,Completed,NaN,C_008459,D_000148
2,B_000003,2025-08-23,08:53:00,Saturday,1,8,Chennai,Loc_28,Loc_1,Auto,...,NaN,Low,Heavy Rain,234.20,1.9,457.03,Cancelled,NaN,C_003471,D_004976
3,B_000004,2025-04-12,10:25:00,Saturday,1,10,Delhi,Loc_16,Loc_30,Bike,...,4.76,Medium,Rain,28.20,1.8,51.03,Completed,NaN,C_002161,D_001173
4,B_000005,2025-08-23,00:08:00,Saturday,1,0,Hyderabad,Loc_22,Loc_31,Bike,...,64.53,Medium,Clear,118.77,1.2,144.73,Completed,NaN,C_005617,D_001175

In [3]:
#Check the Shape of the dataframe
bookings_df.shape

(100000, 22)

In [4]:
#Display the columns of bookings_df
bookings_df.columns

Index(['booking_id', 'booking_date', 'booking_time', 'day_of_week',
       'is_weekend', 'hour_of_day', 'city', 'pickup_location', 'drop_location',
       'vehicle_type', 'ride_distance_km', 'estimated_ride_time_min',
       'actual_ride_time_min', 'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier', 'booking_value', 'booking_status',
       'incomplete_ride_reason', 'customer_id', 'driver_id'],
      dtype='object')

In [5]:
#Check for the null values
bookings_df.isnull().sum()

booking_id                     0
booking_date                   0
booking_time                   0
day_of_week                    0
is_weekend                     0
hour_of_day                    0
city                           0
pickup_location                0
drop_location                  0
vehicle_type                   0
ride_distance_km               0
estimated_ride_time_min        0
actual_ride_time_min       31654
traffic_level                  0
weather_condition              0
base_fare                      0
surge_multiplier               0
booking_value                  0
booking_status                 0
incomplete_ride_reason     91630
customer_id                    0
driver_id                      0
dtype: int64

In [6]:
bookings_df['booking_status'].value_counts()

booking_status
Completed     68346
Cancelled     23284
Incomplete     8370
Name: count, dtype: int64

In [7]:
# Fill missing actual ride times in bookings_df
bookings_df.loc[
    (bookings_df['actual_ride_time_min'].isna()) & 
    (bookings_df['booking_status'] == "Completed"),
    'actual_ride_time_min'
] = bookings_df['estimated_ride_time_min']

bookings_df.loc[
    (bookings_df['actual_ride_time_min'].isna()) & 
    (bookings_df['booking_status'] == "Cancelled"),
    'actual_ride_time_min'
] = 0

bookings_df.loc[
    (bookings_df['actual_ride_time_min'].isna()) & 
    (bookings_df['booking_status'] == "Incomplete") & 
    (bookings_df['incomplete_ride_reason'].notna()),
    'actual_ride_time_min'
] = 0

In [8]:
#Find the counts of each category
bookings_df['incomplete_ride_reason'].value_counts()

incomplete_ride_reason
Driver Delay        4728
Vehicle Issue       1265
App Issue           1221
Customer No-show    1156
Name: count, dtype: int64

In [9]:
#Fill the null values
bookings_df['incomplete_ride_reason']=bookings_df['incomplete_ride_reason'].fillna("Others")

In [10]:
#Check for the null values
bookings_df.isnull().sum()

booking_id                 0
booking_date               0
booking_time               0
day_of_week                0
is_weekend                 0
hour_of_day                0
city                       0
pickup_location            0
drop_location              0
vehicle_type               0
ride_distance_km           0
estimated_ride_time_min    0
actual_ride_time_min       0
traffic_level              0
weather_condition          0
base_fare                  0
surge_multiplier           0
booking_value              0
booking_status             0
incomplete_ride_reason     0
customer_id                0
driver_id                  0
dtype: int64

In [11]:
bookings_df['incomplete_ride_reason'].value_counts()

incomplete_ride_reason
Others              91630
Driver Delay         4728
Vehicle Issue        1265
App Issue            1221
Customer No-show     1156
Name: count, dtype: int64

In [12]:
#Check for duplicates
bookings_df.duplicated().sum()

np.int64(0)

In [13]:
bookings_df.dtypes

booking_id                  object
booking_date                object
booking_time                object
day_of_week                 object
is_weekend                   int64
hour_of_day                  int64
city                        object
pickup_location             object
drop_location               object
vehicle_type                object
ride_distance_km           float64
estimated_ride_time_min    float64
actual_ride_time_min       float64
traffic_level               object
weather_condition           object
base_fare                  float64
surge_multiplier           float64
booking_value              float64
booking_status              object
incomplete_ride_reason      object
customer_id                 object
driver_id                   object
dtype: object

In [14]:
# Convert to datetime first
bookings_df['booking_date'] = pd.to_datetime(bookings_df['booking_date'],format="%Y-%m-%d",errors='coerce').dt.date
bookings_df['booking_time'] = pd.to_datetime(bookings_df['booking_time'],format="%H:%M:%S", errors='coerce').dt.time

In [15]:
bookings_df[['booking_date','booking_time']]

      booking_date booking_time
0       2025-12-11     00:07:00
1       2025-07-07     06:13:00
2       2025-08-23     08:53:00
3       2025-04-12     10:25:00
4       2025-08-23     00:08:00
...            ...          ...
99995   2025-02-09     07:32:00
99996   2025-06-02     08:45:00
99997   2025-08-20     03:36:00
99998   2025-07-30     23:04:00
99999   2025-02-21     02:28:00

[100000 rows x 2 columns]

                                             Customers Dataframe

In [16]:
customers_df=pd.read_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\customers.csv")
customers_df.head()

,customer_id,customer_gender,customer_age,customer_city,customer_signup_days_ago,preferred_vehicle_type,total_bookings,completed_rides,cancelled_rides,incomplete_rides,cancellation_rate,avg_customer_rating,customer_cancel_flag
0,C_000001,Non-Binary,56,Bangalore,556,Cab,10,9,1,0,0.100000,3.8,0
1,C_000002,Male,46,Bangalore,82,Bike,8,7,1,0,0.125000,4.1,0
2,C_000003,Female,32,Delhi,969,Bike,7,4,1,2,0.142857,3.8,0
3,C_000004,Female,60,Hyderabad,549,Bike,11,7,3,1,0.272727,3.7,1
4,C_000005,Non-Binary,25,Hyderabad,359,Bike,9,5,3,1,0.333333,3.8,1

In [17]:
#Display the columns
customers_df.columns

Index(['customer_id', 'customer_gender', 'customer_age', 'customer_city',
       'customer_signup_days_ago', 'preferred_vehicle_type', 'total_bookings',
       'completed_rides', 'cancelled_rides', 'incomplete_rides',
       'cancellation_rate', 'avg_customer_rating', 'customer_cancel_flag'],
      dtype='object')

In [18]:
#Check for duplicates
customers_df.duplicated().sum()

np.int64(0)

In [19]:
#Check for null values
customers_df.isnull().sum()

customer_id                 0
customer_gender             0
customer_age                0
customer_city               0
customer_signup_days_ago    0
preferred_vehicle_type      0
total_bookings              0
completed_rides             0
cancelled_rides             0
incomplete_rides            0
cancellation_rate           0
avg_customer_rating         0
customer_cancel_flag        0
dtype: int64

In [20]:
customers_df['customer_gender'].value_counts()

customer_gender
Male          3369
Female        3359
Non-Binary    3272
Name: count, dtype: int64

In [20]:
customers_df['customer_gender']=customers_df['customer_gender'].replace('Non-Binary','Unknowm',regex=False)

In [21]:
customers_df['customer_gender'].value_counts()

customer_gender
Male       3369
Female     3359
Unknowm    3272
Name: count, dtype: int64

                                                  Drivers Dataframe

In [22]:
drivers_df=pd.read_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\drivers.csv")
drivers_df.head()

,driver_id,driver_age,driver_city,vehicle_type,driver_experience_years,total_assigned_rides,accepted_rides,incomplete_rides,delay_count,acceptance_rate,delay_rate,avg_driver_rating,avg_pickup_delay_min,driver_delay_flag
0,D_000001,39,Bangalore,Auto,1,25,16,0,0,0.64,0.00,4.1,2.0,0
1,D_000002,40,Chennai,Cab,2,14,11,3,2,0.79,0.14,4.8,6.1,1
2,D_000003,26,Bangalore,Auto,12,19,14,3,2,0.74,0.11,4.1,2.6,1
3,D_000004,46,Chennai,Auto,3,18,13,2,2,0.72,0.11,4.2,2.6,1
4,D_000005,32,Chennai,Bike,7,18,16,1,1,0.89,0.06,4.8,4.9,0

In [24]:
drivers_df.shape

(5000, 14)

delay_rate=delay_count/total_assigned_rides
=2/14=0.14 
which is the delay_rate specified in the table.

driver_delay_flag is based on the delay_rate
if delay_rate >0.1,driver_delay_flag =1
else driver_delay_flag =0

In [25]:
drivers_df[['delay_count','delay_rate','avg_pickup_delay_min','driver_delay_flag']].head(10)

   delay_count  delay_rate  avg_pickup_delay_min  driver_delay_flag
0            0        0.00                   2.0                  0
1            2        0.14                   6.1                  1
2            2        0.11                   2.6                  1
3            2        0.11                   2.6                  1
4            1        0.06                   4.9                  0
5            2        0.07                   3.0                  0
6            1        0.04                   4.6                  0
7            0        0.00                   3.0                  0
8            1        0.03                   2.4                  0
9            2        0.08                   4.2                  0

In [26]:
drivers_df.columns

Index(['driver_id', 'driver_age', 'driver_city', 'vehicle_type',
       'driver_experience_years', 'total_assigned_rides', 'accepted_rides',
       'incomplete_rides', 'delay_count', 'acceptance_rate', 'delay_rate',
       'avg_driver_rating', 'avg_pickup_delay_min', 'driver_delay_flag'],
      dtype='object')

In [27]:
drivers_df.duplicated().sum()

np.int64(0)

In [28]:
drivers_df.isnull().sum()

driver_id                  0
driver_age                 0
driver_city                0
vehicle_type               0
driver_experience_years    0
total_assigned_rides       0
accepted_rides             0
incomplete_rides           0
delay_count                0
acceptance_rate            0
delay_rate                 0
avg_driver_rating          0
avg_pickup_delay_min       0
driver_delay_flag          0
dtype: int64

                                        Location Demand Dataframe

In [29]:
location_demand_df=pd.read_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\location_demand.csv")
location_demand_df.head()

,city,pickup_location,hour_of_day,vehicle_type,total_requests,completed_rides,cancelled_rides,avg_wait_time_min,avg_surge_multiplier,demand_level
0,Bangalore,Loc_1,0,Auto,2,2,0,87.940000,1.400000,Low
1,Bangalore,Loc_1,0,Bike,5,5,0,68.088000,1.460000,Low
2,Bangalore,Loc_1,0,Cab,6,5,0,50.913333,1.733333,Medium
3,Bangalore,Loc_1,1,Auto,3,2,0,72.883333,1.566667,Low
4,Bangalore,Loc_1,1,Bike,7,6,1,33.374286,1.242857,Medium

In [30]:
location_demand_df['city'].unique()

array(['Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Mumbai'],
      dtype=object)

In [31]:
location_demand_df.columns

Index(['city', 'pickup_location', 'hour_of_day', 'vehicle_type',
       'total_requests', 'completed_rides', 'cancelled_rides',
       'avg_wait_time_min', 'avg_surge_multiplier', 'demand_level'],
      dtype='object')

In [32]:
location_demand_df.duplicated().sum()

np.int64(0)

In [33]:
location_demand_df.isnull().sum()

city                    0
pickup_location         0
hour_of_day             0
vehicle_type            0
total_requests          0
completed_rides         0
cancelled_rides         0
avg_wait_time_min       0
avg_surge_multiplier    0
demand_level            0
dtype: int64

                                          Time Features

In [34]:
time_features_df=pd.read_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\time_features.csv")
time_features_df.head()

,datetime,hour_of_day,day_of_week,is_weekend,is_holiday,peak_time_flag,season
0,2025-01-01 00:00:00,0,Wednesday,0,0,0,Winter
1,2025-01-01 01:00:00,1,Wednesday,0,0,0,Winter
2,2025-01-01 02:00:00,2,Wednesday,0,0,0,Winter
3,2025-01-01 03:00:00,3,Wednesday,0,0,0,Winter
4,2025-01-01 04:00:00,4,Wednesday,0,0,0,Winter

In [35]:
time_features_df.columns

Index(['datetime', 'hour_of_day', 'day_of_week', 'is_weekend', 'is_holiday',
       'peak_time_flag', 'season'],
      dtype='object')

In [36]:
time_features_df.duplicated().sum()

np.int64(0)

In [37]:
time_features_df.isnull().sum()

datetime          0
hour_of_day       0
day_of_week       0
is_weekend        0
is_holiday        0
peak_time_flag    0
season            0
dtype: int64

In [38]:
time_features_df.dtypes

datetime          object
hour_of_day        int64
day_of_week       object
is_weekend         int64
is_holiday         int64
peak_time_flag     int64
season            object
dtype: object

In [39]:
time_features_df['datetime']=pd.to_datetime(time_features_df['datetime'],format="%Y-%m-%d %H:%M:%S",errors="coerce")

In [40]:
time_features_df['datetime'].dtype

dtype('<M8[ns]')

                                             Feature Engineering

                                             Fare_per_KM

In [41]:
#fare_per_km=booking_value/ride_distance_km

bookings_df['fare_per_km'] = bookings_df.apply(
    lambda row: row['booking_value'] / row['ride_distance_km']
    if row['ride_distance_km'] not in [0, None, float('nan')]
    else None,
    axis=1
)

In [42]:
bookings_df['fare_per_km']

0        21.144080
1        48.174767
2        28.246601
3        50.029412
4        11.719028
           ...
99995    23.705357
99996    31.384134
99997    31.879789
99998    28.975514
99999    33.137690
Name: fare_per_km, Length: 100000, dtype: float64

                                                    Fare_per_Min

In [43]:
bookings_df.columns

Index(['booking_id', 'booking_date', 'booking_time', 'day_of_week',
       'is_weekend', 'hour_of_day', 'city', 'pickup_location', 'drop_location',
       'vehicle_type', 'ride_distance_km', 'estimated_ride_time_min',
       'actual_ride_time_min', 'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier', 'booking_value', 'booking_status',
       'incomplete_ride_reason', 'customer_id', 'driver_id', 'fare_per_km'],
      dtype='object')

In [44]:
bookings_df['fare_per_min'] = np.where(
    bookings_df['actual_ride_time_min'] > 0,
    bookings_df['booking_value'] / bookings_df['actual_ride_time_min'],
    bookings_df['booking_value'] / bookings_df['estimated_ride_time_min']
)

In [45]:
bookings_df['fare_per_min']

0         3.201296
1        11.018212
2         9.413594
3        10.720588
4         2.242833
           ...
99995     4.924127
99996     3.997075
99997     7.705300
99998     3.799713
99999     6.995981
Name: fare_per_min, Length: 100000, dtype: float64

                                                      Rush_hour_flag

In [46]:
# Filter only peak hours
peak_df = time_features_df[time_features_df['peak_time_flag'] == 1].copy()
peak_df.head(22)

,datetime,hour_of_day,day_of_week,is_weekend,is_holiday,peak_time_flag,season
8,2025-01-01 08:00:00,8,Wednesday,0,0,1,Winter
9,2025-01-01 09:00:00,9,Wednesday,0,0,1,Winter
10,2025-01-01 10:00:00,10,Wednesday,0,0,1,Winter
17,2025-01-01 17:00:00,17,Wednesday,0,0,1,Winter
18,2025-01-01 18:00:00,18,Wednesday,0,0,1,Winter
19,2025-01-01 19:00:00,19,Wednesday,0,0,1,Winter
20,2025-01-01 20:00:00,20,Wednesday,0,0,1,Winter
32,2025-01-02 08:00:00,8,Thursday,0,0,1,Winter
33,2025-01-02 09:00:00,9,Thursday,0,0,1,Winter
34,2025-01-02 10:00:00,10,Thursday,0,0,1,Winter
41,2025-01-02 17:00:00,17,Thursday,0,0,1,Winter
42,2025-01-02 18:00:00,18,Thursday,0,0,1,Winter
43,2025-01-02 19:00:00,19,Thursday,0,0,1,Winter
44,2025-01-02 20:00:00,20,Thursday,0,0,1,Winter
56,2025-01-03 08:00:00,8,Friday,0,0,1,Winter
57,2025-01-03 09:00:00,9,Friday,0,0,1,Winter
58,2025-01-03 10:00:00,10,Friday,0,0,1,Winter
65,2025-01-03 17:00:00,17,Friday,0,0,1,Winter
66,2025-01-03 18:00:00,18,Friday,0,0,1,Winter
67,2025-01-03 19:00:00,19,Friday,0,0,1,Winter
68,2025-01-03 20:00:00,20,Friday,0,0,1,Winter
80,2025-01-04 08:00:00,8,Saturday,1,0,1,Winter

So it is obvious that there are two peak hour intervals in a day 
8am to 10am  and 
5pm to 8 pm

In [47]:
#Create a new column rush_hour_flag  in bookings_df
peak_mask= (bookings_df['hour_of_day'] >=8) & (bookings_df['hour_of_day']<=10) | (bookings_df['hour_of_day'] >=17) & (bookings_df['hour_of_day']<=20)
bookings_df['rush_hour_flag']=np.where(peak_mask,1,0)

                                               LONG DISTANCE FLAG

In [48]:
print("Then min ride distance is ",bookings_df['ride_distance_km'].min())
print("Then max ride distance is ",bookings_df['ride_distance_km'].max())

Then min ride distance is  1.0
Then max ride distance is  25.0

Then min ride distance is  1.0
Then max ride distance is  25.0
So I assume long distance rides are over 15km  (60 % of 25km)

In [49]:
#Create a new column long distance flag
bookings_df['long_distance_flag']=np.where(bookings_df['ride_distance_km']>15,1,0)

In [50]:
#Display the new column
bookings_df[['ride_distance_km','long_distance_flag']]

       ride_distance_km  long_distance_flag
0                  7.01                   0
1                  9.67                   0
2                 16.18                   1
3                  1.02                   0
4                 12.35                   0
...                 ...                 ...
99995             12.32                   0
99996              9.58                   0
99997              7.57                   0
99998             22.87                   1
99999             15.76                   1

[100000 rows x 2 columns]

                                                  CITY PAIR

In [51]:
#Create a new column city pair 
bookings_df['city_pair']=bookings_df['pickup_location'].astype(str) + " " + bookings_df['drop_location']

In [52]:
bookings_df['city_pair']

0        Loc_19 Loc_16
1        Loc_32 Loc_38
2         Loc_28 Loc_1
3        Loc_16 Loc_30
4        Loc_22 Loc_31
             ...
99995    Loc_27 Loc_10
99996     Loc_43 Loc_2
99997    Loc_20 Loc_38
99998      Loc_5 Loc_3
99999    Loc_11 Loc_15
Name: city_pair, Length: 100000, dtype: object

                                            Driver_Reliability_Score

📊 Reliability Score Components (Accepted-Rides Based)

Incompletion Rate=Incompleted Rides/Total Assigned Rides

Completion Rate=Completed Rides/Total Assigned Rides

Cancellation Rate=Cancelled Rides/Total Assigned Rides


Delay Factor=1−Delay Rate

Rating Normalized=Avg Driver Rating/5


🧮 Formula
Driver Reliability Score=0.2 *incompletion_rate + 0.2 *cancellation_rate +  0.3 * completion_rate+0.2*(1−Delay Rate) + 0.3*Rating Norm

Incompletion and Cancellation  Rate show the neg aspects of a driver when he takes rides.

Completion Rate shows reliability once accepted.

Delay & Rating capture punctuality and service quality.


['driver_id', 'driver_age', 'driver_city', 'vehicle_type',
       'driver_experience_years', 'total_assigned_rides', 'accepted_rides',
       'incomplete_rides', 'delay_count', 'acceptance_rate', 'delay_rate',
       'avg_driver_rating', 'avg_pickup_delay_min', 'driver_delay_flag'],

In [78]:
def driver_reliability_score(driver_id, drivers_df, bookings_df):
    # Filter driver record
    driver_record_df = drivers_df[drivers_df['driver_id'] == driver_id].reset_index(drop=True)

    # Completion Rate (fetched from bookings table)
    comp_count_df = bookings_df[(bookings_df['booking_status'] == "Completed") &
                                (bookings_df['driver_id'] == driver_id)]
    completed_rides_count = len(comp_count_df)
    completion_rate = completed_rides_count / driver_record_df.loc[0, 'total_assigned_rides']

    # Incompletion Rate (fetched from bookings table)
    incomp_count_df = bookings_df[(bookings_df['booking_status'] == 'Incomplete') &
                                (bookings_df['driver_id'] == driver_id)]
    incompleted_rides_count = len(incomp_count_df)
    incompletion_rate = incompleted_rides_count / driver_record_df.loc[0, 'total_assigned_rides']


    # Cancellation Rate (fetched from bookings table)
    cancelled_count_df = bookings_df[(bookings_df['booking_status'] == 'Cancelled') &
                                (bookings_df['driver_id'] == driver_id)]
    cancelled_rides_count = len(cancelled_count_df)
    cancellation_rate = cancelled_rides_count / driver_record_df.loc[0, 'total_assigned_rides']


    # Delay factor
    delay_factor = 1 - driver_record_df.loc[0, 'delay_rate']

    # Normalized Rating
    norm_rating = driver_record_df.loc[0, 'avg_driver_rating'] / 5

    # Reliability Score
    driver_rel_score = (0.2 *incompletion_rate+
                        0.2 *+cancellation_rate+
                        
                        0.3 * completion_rate +
                        0.2 * delay_factor +
                        0.3 * norm_rating)

    
    drivers_df.loc[drivers_df['driver_id']==driver_id,'reliability_score'] = driver_rel_score
      
    
drivers_lst=drivers_df['driver_id'].unique()
drivers_df['reliability_score'] = 0
for i in drivers_lst:
  driver_reliability_score(i,drivers_df,bookings_df)

drivers_df.head(10)

,driver_id,driver_age,driver_city,vehicle_type,driver_experience_years,total_assigned_rides,accepted_rides,incomplete_rides,delay_count,acceptance_rate,delay_rate,avg_driver_rating,avg_pickup_delay_min,driver_delay_flag,reliability_score
0,D_000001,39,Bangalore,Auto,1,25,16,0,0,0.64,0.00,4.1,2.0,0,0.710000
1,D_000002,40,Chennai,Cab,2,14,11,3,2,0.79,0.14,4.8,6.1,1,0.717143
2,D_000003,26,Bangalore,Auto,12,19,14,3,2,0.74,0.11,4.1,2.6,1,0.681895
3,D_000004,46,Chennai,Auto,3,18,13,2,2,0.72,0.11,4.2,2.6,1,0.691111
4,D_000005,32,Chennai,Bike,7,18,16,1,1,0.89,0.06,4.8,4.9,0,0.759333
5,D_000006,31,Chennai,Bike,6,30,27,2,2,0.90,0.07,4.4,3.0,0,0.733333
6,D_000007,38,Mumbai,Cab,14,24,19,2,1,0.79,0.04,4.0,4.6,0,0.702833
7,D_000008,47,Mumbai,Cab,7,18,15,2,0,0.83,0.00,4.5,3.0,0,0.742222
8,D_000009,52,Delhi,Auto,11,30,22,1,1,0.73,0.03,4.1,2.4,0,0.710000
9,D_000010,53,Mumbai,Cab,5,24,18,2,2,0.75,0.08,4.4,4.2,0,0.714667

                                        Customer_Loyalty_Score

In [83]:
def customer_score():
    #Find the booking_freq_norm
    customers_df['booking_freq']=customers_df['total_bookings'] / customers_df['customer_signup_days_ago']
    max_freq=customers_df['booking_freq'].max()
    customers_df['booking_freq_norm']=customers_df['booking_freq']/max_freq

    #Find the completion rate
    customers_df['completion_rate'] = customers_df['completed_rides'] / customers_df['total_bookings']

    #cancellation_factor
    customers_df['cancellation_factor']=1-customers_df['cancellation_rate']

      
    #Rating Normalized
    customers_df['rating_norm']=customers_df['avg_customer_rating']/5

   
    # Calculate incompletion_rate
    customers_df['incompletion_rate'] = (customers_df['incomplete_rides'] / customers_df['total_bookings']).fillna(0)

    # Convert to incompletion_factor (higher incomplete rides → lower factor)
    customers_df['incompletion_factor'] = 1 - customers_df['incompletion_rate']

    #loyalty_score formula with diff weights
    customers_df['loyalty_score'] = (
    0.30 * customers_df['booking_freq_norm'] +
    0.40 * customers_df['completion_rate'] +
    0.20 * customers_df['cancellation_factor'] +
    0.30 * customers_df['rating_norm'] +
    0.20 * customers_df['incompletion_factor']
    ) * 100

    customers_df['loyalty_score'] = round(customers_df['loyalty_score'], 2)

       
customer_score()
customers_df.head(5)

,customer_id,customer_gender,customer_age,customer_city,customer_signup_days_ago,preferred_vehicle_type,total_bookings,completed_rides,cancelled_rides,incomplete_rides,...,avg_customer_rating,customer_cancel_flag,booking_freq,booking_freq_norm,completion_rate,cancellation_factor,rating_norm,incompletion_rate,incompletion_factor,loyalty_score
0,C_000001,Unknowm,56,Bangalore,556,Cab,10,9,1,0,...,3.8,0,0.017986,0.032797,0.900000,0.900000,0.76,0.000000,1.000000,97.78
1,C_000002,Male,46,Bangalore,82,Bike,8,7,1,0,...,4.1,0,0.097561,0.177905,0.875000,0.875000,0.82,0.000000,1.000000,102.44
2,C_000003,Female,32,Delhi,969,Bike,7,4,1,2,...,3.8,0,0.007224,0.013173,0.571429,0.857143,0.76,0.285714,0.714286,77.48
3,C_000004,Female,60,Hyderabad,549,Bike,11,7,3,1,...,3.7,1,0.020036,0.036537,0.636364,0.727273,0.74,0.090909,0.909091,81.48
4,C_000005,Unknowm,25,Hyderabad,359,Bike,9,5,3,1,...,3.8,1,0.025070,0.045715,0.555556,0.666667,0.76,0.111111,0.888889,77.50

                                    Save all the four csv files to SQL database

In [84]:
#create SQL connection object
def create_connection():
 from mysql.connector import Error
 
 try:
   connection=mysql.connector.connect(host="localhost",username="root",password="root",database="rapido")
   if connection.is_connected():
    print("Successfully connected to MYSQL")
    return connection
 except Error as err:
    print(f"Error code in connecting with MYSQL server :{err} ")
    return None
  
conn=create_connection()

Successfully connected to MYSQL

In [85]:
#write the csv files to SQL tables usign SQLALCHEMY
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:root@localhost/rapido")
with engine.begin() as conn:
    bookings_df.to_sql(
        name="bookings_df_cleaned",
        con=conn,          # <-- use conn here
        if_exists="replace",
        index=False,
        chunksize=1000     # optional, avoids packet size issues
    )


    customers_df.to_sql(
        name="customers_df_cleaned",
        con=conn,          # <-- use conn here
        if_exists="replace",
        index=False,
        chunksize=1000     # optional, avoids packet size issues
    )

    drivers_df.to_sql(
        name="drivers_df_cleaned",
        con=conn,          # <-- use conn here
        if_exists="replace",
        index=False,
        chunksize=1000     # optional, avoids packet size issues
    )

    location_demand_df.to_sql(
        name="location_demand_df_cleaned",
        con=conn,          # <-- use conn here
        if_exists="replace",
        index=False,
        chunksize=1000     # optional, avoids packet size issues
    )

    time_features_df.to_sql(
        name="time_features_df_cleaned",
        con=conn,          # <-- use conn here
        if_exists="replace",
        index=False,
        chunksize=1000     # optional, avoids packet size issues
    )

Save all the cleaned dataframes to csv files

In [86]:
bookings_df.to_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\bookings.csv", index=False)
customers_df.to_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\customers.csv", index=False)
drivers_df.to_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\drivers.csv", index=False)
location_demand_df.to_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\location_demand.csv", index=False)
time_features_df.to_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\time_features.csv", index=False)

In [58]:
bookings_df.columns

Index(['booking_id', 'booking_date', 'booking_time', 'day_of_week',
       'is_weekend', 'hour_of_day', 'city', 'pickup_location', 'drop_location',
       'vehicle_type', 'ride_distance_km', 'estimated_ride_time_min',
       'actual_ride_time_min', 'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier', 'booking_value', 'booking_status',
       'incomplete_ride_reason', 'customer_id', 'driver_id', 'fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag', 'city_pair'],
      dtype='object')

                                        Categorical Encoding

The original columns of bookings_df are 
Index(['booking_id', 'booking_date', 'booking_time', 'day_of_week',
       'is_weekend', 'hour_of_day', 'city', 'pickup_location', 'drop_location',
       'vehicle_type', 'ride_distance_km', 'estimated_ride_time_min',
       'actual_ride_time_min', 'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier', 'booking_value', 'booking_status',
       'incomplete_ride_reason', 'customer_id', 'driver_id', 'fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag', 'city_pair'],
      dtype='object')


      The features ( X) needed for Fare prediction model building are

      'day_of_week','is_weekend', 'hour_of_day', 'city', 'pickup_location', 'drop_location',
       'vehicle_type', 'ride_distance_km', 'estimated_ride_time_min',
       'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier','fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag', 'city_pair'

     Of these columns,the cateogorical columns which need to be encoded before Fare prediction model building are
     'day_of_week','city','vehicle_type','traffic_level', 'weather_condition'


    'pickup_location', 'drop_location' need to be data cleaned to make it numerical.

In [59]:
bookings_df=pd.read_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\bookings.csv")
bookings_df.head(2)

,booking_id,booking_date,booking_time,day_of_week,is_weekend,hour_of_day,city,pickup_location,drop_location,vehicle_type,...,booking_value,booking_status,incomplete_ride_reason,customer_id,driver_id,fare_per_km,fare_per_min,rush_hour_flag,long_distance_flag,city_pair
0,B_000001,2025-12-11,00:07:00,Thursday,0,0,Mumbai,Loc_19,Loc_16,Bike,...,148.22,Cancelled,Others,C_005097,D_004592,21.144080,3.201296,0,0,Loc_19 Loc_16
1,B_000002,2025-07-07,06:13:00,Monday,0,6,Mumbai,Loc_32,Loc_38,Cab,...,465.85,Completed,Others,C_008459,D_000148,48.174767,11.018212,0,0,Loc_32 Loc_38

In [60]:
#Build a new df for model building
fare_pred_model_df=bookings_df[['day_of_week','is_weekend', 'hour_of_day', 'city', 'pickup_location', 'drop_location',
       'vehicle_type', 'ride_distance_km', 'estimated_ride_time_min',
       'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier','fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag', 'city_pair','booking_value']]

In [61]:
#data cleaning for pickup_location', 'drop_location' ---   loc_19 becomes 19 after data cleaning
fare_pred_model_df['pickup_location']=fare_pred_model_df['pickup_location'].str.strip().str.lower().str.replace(r"loc_","",regex=True)
fare_pred_model_df['drop_location']=fare_pred_model_df['drop_location'].str.strip().str.lower().str.replace(r"loc_","",regex=True)
#fare_pred_model_df['city_pair']=fare_pred_model_df['city_pair'].str.strip().str.lower().str.replace(r"loc_","",regex=True)
fare_pred_model_df[['pickup_location','drop_location']]

      pickup_location drop_location
0                  19            16
1                  32            38
2                  28             1
3                  16            30
4                  22            31
...               ...           ...
99995              27            10
99996              43             2
99997              20            38
99998               5             3
99999              11            15

[100000 rows x 2 columns]

                                 DAY OF WEEK -ORDINAL ENCODING

In [62]:
print(fare_pred_model_df['day_of_week'].unique())

['Thursday' 'Monday' 'Saturday' 'Tuesday' 'Sunday' 'Wednesday' 'Friday']

In [63]:
#categorical encoding for day of week
ord_encoder=OrdinalEncoder(categories=[['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']])

fare_pred_model_df['day_of_week']=ord_encoder.fit_transform(fare_pred_model_df[['day_of_week']])
fare_pred_model_df['day_of_week']

0        4.0
1        1.0
2        6.0
3        6.0
4        6.0
        ...
99995    0.0
99996    1.0
99997    3.0
99998    3.0
99999    5.0
Name: day_of_week, Length: 100000, dtype: float64

           CITY ONE HOT ENCODING

In [64]:
bookings_df['city'].value_counts()

city
Delhi        20161
Chennai      20044
Bangalore    19947
Mumbai       19943
Hyderabad    19905
Name: count, dtype: int64

In [65]:
ohe = OneHotEncoder(sparse_output=False)

city_encoded = ohe.fit_transform(fare_pred_model_df[['city']])

# Add back to DataFrame
city_encoded_df = pd.DataFrame(city_encoded, columns=ohe.get_feature_names_out(['city']))
fare_pred_model_df = pd.concat([fare_pred_model_df, city_encoded_df], axis=1)
fare_pred_model_df.head(2)

,day_of_week,is_weekend,hour_of_day,city,pickup_location,drop_location,vehicle_type,ride_distance_km,estimated_ride_time_min,traffic_level,...,fare_per_min,rush_hour_flag,long_distance_flag,city_pair,booking_value,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai
0,4.0,0,0,Mumbai,19,16,Bike,7.01,46.30,High,...,3.201296,0,0,Loc_19 Loc_16,148.22,0.0,0.0,0.0,0.0,1.0
1,1.0,0,6,Mumbai,32,38,Cab,9.67,43.54,Medium,...,11.018212,0,0,Loc_32 Loc_38,465.85,0.0,0.0,0.0,0.0,1.0

VEHICLE TYPE ENCODING

In [66]:
bookings_df['vehicle_type'].value_counts()

vehicle_type
Cab     33415
Bike    33394
Auto    33191
Name: count, dtype: int64

In [67]:
ohe = OneHotEncoder(sparse_output=False)
vehicle_encoded = ohe.fit_transform(fare_pred_model_df[['vehicle_type']])

# Add back to DataFrame
vehicle_type_encoded_df = pd.DataFrame(vehicle_encoded, columns=ohe.get_feature_names_out(['vehicle_type']))
fare_pred_model_df = pd.concat([fare_pred_model_df, vehicle_type_encoded_df], axis=1)
fare_pred_model_df.head(2)

,day_of_week,is_weekend,hour_of_day,city,pickup_location,drop_location,vehicle_type,ride_distance_km,estimated_ride_time_min,traffic_level,...,city_pair,booking_value,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab
0,4.0,0,0,Mumbai,19,16,Bike,7.01,46.30,High,...,Loc_19 Loc_16,148.22,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0,6,Mumbai,32,38,Cab,9.67,43.54,Medium,...,Loc_32 Loc_38,465.85,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

                   ORDINAL ENCODING FOR TRAFFIC CONDITIONS

In [68]:
fare_pred_model_df['traffic_level'].value_counts()

traffic_level
High      33667
Medium    33198
Low       33135
Name: count, dtype: int64

In [ ]:
# Clean the column first (strip spaces, unify case)
fare_pred_model_df['traffic_level'] = fare_pred_model_df['traffic_level'].str.strip().str.title()

# Define encoder with explicit order
ord_encoder = OrdinalEncoder(
    categories=[['Low','Medium','High']]   
)

# Fit-transform
fare_pred_model_df['traffic_level'] = ord_encoder.fit_transform(
    fare_pred_model_df[['traffic_level']]
)

In [70]:
fare_pred_model_df['traffic_level']

0        2.0
1        1.0
2        0.0
3        1.0
4        1.0
        ...
99995    1.0
99996    2.0
99997    1.0
99998    2.0
99999    1.0
Name: traffic_level, Length: 100000, dtype: float64

WEATHER CONDITIONS ENCODING

In [71]:
fare_pred_model_df['weather_condition'].value_counts()

weather_condition
Heavy Rain    33616
Clear         33200
Rain          33184
Name: count, dtype: int64

In [72]:

ohe = OneHotEncoder(sparse_output=False)

weather_encoded = ohe.fit_transform(fare_pred_model_df[['weather_condition']])

# Add back to DataFrame
weather_encoded_df = pd.DataFrame(weather_encoded, columns=ohe.get_feature_names_out(['weather_condition']))
fare_pred_model_df = pd.concat([fare_pred_model_df, weather_encoded_df], axis=1)
fare_pred_model_df.head(2)

,day_of_week,is_weekend,hour_of_day,city,pickup_location,drop_location,vehicle_type,ride_distance_km,estimated_ride_time_min,traffic_level,...,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab,weather_condition_Clear,weather_condition_Heavy Rain,weather_condition_Rain
0,4.0,0,0,Mumbai,19,16,Bike,7.01,46.30,2.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,1.0,0,6,Mumbai,32,38,Cab,9.67,43.54,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [73]:
fare_pred_model_df.columns

Index(['day_of_week', 'is_weekend', 'hour_of_day', 'city', 'pickup_location',
       'drop_location', 'vehicle_type', 'ride_distance_km',
       'estimated_ride_time_min', 'traffic_level', 'weather_condition',
       'base_fare', 'surge_multiplier', 'fare_per_km', 'fare_per_min',
       'rush_hour_flag', 'long_distance_flag', 'city_pair', 'booking_value',
       'city_Bangalore', 'city_Chennai', 'city_Delhi', 'city_Hyderabad',
       'city_Mumbai', 'vehicle_type_Auto', 'vehicle_type_Bike',
       'vehicle_type_Cab', 'weather_condition_Clear',
       'weather_condition_Heavy Rain', 'weather_condition_Rain'],
      dtype='object')

In [74]:
fare_pred_model_df=fare_pred_model_df.drop(columns=['city','vehicle_type','weather_condition','city_pair'])

fare_pred_model_df.columns

Index(['day_of_week', 'is_weekend', 'hour_of_day', 'pickup_location',
       'drop_location', 'ride_distance_km', 'estimated_ride_time_min',
       'traffic_level', 'base_fare', 'surge_multiplier', 'fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag', 'booking_value',
       'city_Bangalore', 'city_Chennai', 'city_Delhi', 'city_Hyderabad',
       'city_Mumbai', 'vehicle_type_Auto', 'vehicle_type_Bike',
       'vehicle_type_Cab', 'weather_condition_Clear',
       'weather_condition_Heavy Rain', 'weather_condition_Rain'],
      dtype='object')

In [75]:
fare_pred_model_df=fare_pred_model_df.reindex(columns=['day_of_week', 'is_weekend', 'hour_of_day', 'pickup_location',
       'drop_location', 'ride_distance_km', 'estimated_ride_time_min',
       'traffic_level', 'base_fare', 'surge_multiplier', 'fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag', 
       'city_Bangalore', 'city_Chennai', 'city_Delhi', 'city_Hyderabad',
       'city_Mumbai', 'vehicle_type_Auto', 'vehicle_type_Bike',
       'vehicle_type_Cab', 'weather_condition_Clear',
       'weather_condition_Heavy Rain', 'weather_condition_Rain','booking_value'])

In [76]:
fare_pred_model_df.columns

Index(['day_of_week', 'is_weekend', 'hour_of_day', 'pickup_location',
       'drop_location', 'ride_distance_km', 'estimated_ride_time_min',
       'traffic_level', 'base_fare', 'surge_multiplier', 'fare_per_km',
       'fare_per_min', 'rush_hour_flag', 'long_distance_flag',
       'city_Bangalore', 'city_Chennai', 'city_Delhi', 'city_Hyderabad',
       'city_Mumbai', 'vehicle_type_Auto', 'vehicle_type_Bike',
       'vehicle_type_Cab', 'weather_condition_Clear',
       'weather_condition_Heavy Rain', 'weather_condition_Rain',
       'booking_value'],
      dtype='object')

In [77]:
fare_pred_model_df.to_csv(r"D:\VS_CODE\Rapido\drive-download-20260323T152350Z-3-001\cleaned_csv_files\fare_pred_model_df.csv",index=False)